### PR TITLE
Initial lwjgl rendering

### PR DESCRIPTION
**Pull request by quete12**
Code to load and render any Obj File on screen with lwjgl.

This is just the beginning. There is already some refactoring needed but I'll deal with that when we get to Terrains.

### CODE REVIEW

**Comment by ghost** [comment]
Sorry but over 200,000 lines of changes is far too much to review all at once, very happy to review one self-contained chunk at a time :)

**Comment by quete12** [comment]
Wait! The source file for the dragon Object is 200000 lines. It contains the coordinates, rotation and texture points of each mesh vertex.

**Comment by ghost** [comment]
lol ok my mistake! Will re-open and review

**Comment by ghost** [comment]
It's still too big to do a proper review really, there seems to be a load of different parts it could be split into, shaders, resources, resource loading, camera, game objects, rendering, peripheral input, game loop, window management. It all looks ok from a shallow overview, but it still needs breaking down into separate units of work really. PRs that are small self-contained units are much easier and quicker to understand and will be merged much quicker. Still going to have to close this one am afraid, but am very happy to review it in smaller chunks :)

**Comment by ghost** [comment]
If you want a hand pulling out smaller chunks I'm happy to help

**Comment by ghost** [comment]
@quete12 I've created a bunch of projects to help separate out the chunks of work, there's a fair few sub-tasks in them that this PR can provide the basis for. Is that ok with you? I don't mind doing it if you want or if you'd prefer to just say!

**Pull request closed without merging**
